services:
  vscode:
    container_name: vscode-remote-tunnels
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MACHINE_NAME=<MACHINE_NAME>
    volumes:
      - ./root:/root
    restart: unless-stopped
